name: Add And Update Metadata
on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * 1/4"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: go get .

      - name: Build
        run: go build -v

      - name: Setup DB
        run: ./similar init

      - name: Run Add new Manga
        run: ./similar mangadex add

      - name: Update manga metadata since last run
        run: ./similar mangadex metadata

      - name: Update mappings
        run: ./similar calculate mappings

      - name: Create PR for Manga metadata changes
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            data/manga/*
            data/mappings/*
            data/last_metadata_update.txt
          commit-message: Update Manga metadata and MU mapping
          branch: auto-update
          title: Update Manga metadata and MU mapping
          delete-branch: true

