name: test
on:
  workflow_dispatch:
jobs:

  build:
    name: Process
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: go get .

      - name: Build
        run: go build -v

      - name: Setup DB
        run: ./similar init

      - name: Run Add new Manga
        run: ./similar mangadex add

      - name: switch directories
        run: |
          cd ..

      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          repository: CarlosEsco/data
          refs: update

      - name: cp similar files
        run: |
          ls
          cd data
          cp ../similar/data/similar/ similar

      - name: Create PR for Similar data
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            data/similar/*
          commit-message: Update Similar Mappings
          branch: auto-update
          title: Update Similar Mappings
          delete-branch: true




